### ISSUE TITLE
Error installing Pillow from requirements.txt

### ISSUE THREAD

**Issue by moue** [jsani0102/advocateonline#1]
I could not install the Pillow version in requirements.txt (2.0.0), but I was able to successfully install Pillow-2.7.0 instead. 

This is the error I got when running ```pip install -r requirements.txt```:
```python
Command "/Users/Yuqi/.virtualenvs/jay/bin/python -c "import setuptools, tokenize;__file__='/var/folders/63/jl2sb1k563s_npdwkr2p7phm0000gn/T/pip-build-6oDBDH/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/63/jl2sb1k563s_npdwkr2p7phm0000gn/T/pip-7_pf67-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Yuqi/.virtualenvs/jay/include/site/python2.7" failed with error code 1 in /var/folders/63/jl2sb1k563s_npdwkr2p7phm0000gn/T/pip-build-6oDBDH/Pillow
```

**Comment by jsani0102** [comment]
Please ask Brandon about this. When setting up the repo initially, versions of Pillow above 2.0 resulted in errors with the Image library. I had to downgrade to 2.0 in order to run the server

**Comment by moue** [comment]
Interesting. That shouldn't be happening. I will continue to use Pillow version 2.7.0 to view your site as version 2.0.0 throws an error for me. Is Pillow relevant to your API?

**Comment by jsani0102** [comment]
No, it is not. It just raised problems when I was trying to run the server initially. I don't think it should have any problems receiving the Images for the art API call, since we are not processing them but instead just using the URLs as strings.
