### ISSUE TITLE
ImportError: No module named rest_framework

### ISSUE THREAD

**Issue by moue** [jsani0102/advocateonline#2]
Got the error ```ImportError: No module named rest_framework``` when I tried to run ```./manage.py runserver```. Please make sure to update the requirements file after install new packages: ```pip freeze > requirements.txt```. When working in a team, it's important to make setup as easy as possible.

**Comment by jsani0102** [comment]
Okay, I installed djangorestframework using 'pip install djangorestframework' to set up the api. I will update the requirements.txt and will repush.
